from SinglyLinkedList import SinglyLinkedList
myList=SinglyLinkedList()
myList.addFirst(6)
# myList.addFirst(6)
# myList.addFirst(6)
myList.addFirst(18)
myList.addFirst(3)
myList.addFirst(5)
myList.display()
myList.addLast(11)
myList.addLast(3)
myList.addLast(18)
myList.addLast(5)
myList.addLast(18)
myList.addLast(3)
myList.display()
print(f"Number of nodes: ", myList.countNodes())
#Add node at Pos
# x = int(input("Input value to add x = "))
# pos = int(input("Input position to add pos = "))
# myList.addAtPos(x,pos)
# myList.display()
#Remove First
# myList.removeFirst()
# myList.display()
#Remove Last
# myList.removeLast2()
# myList.display()
# print("\nRemove at pos")
# pos = int(input("Input position to remove pos = "))
# myList.removeAtPos(pos)
# myList.display()
# f = myList.getValueAtFirst()
# l = myList.getValueAtLast()
# print(f"First value: {f}; Last value: {l}")
# print("\nGet value at pos")
# pos = int(input("Input position to get value pos = "))
# val=myList.getValueAtPos(pos)
# print(f"The value of node at {pos} is: {val}")
# print("\nSet value x at pos")
# x = int(input("Input value x = "))
# pos = int(input("Input position to modify value pos = "))
# myList.setValueAtPos(x,pos)
# myList.display()
# print("\nRemove all node x")
# x = int(input("Input value to remove x = "))
# myList.removeAllNode(x)
# myList.display()
# print("\nFind the 1st position of x")
# x = int(input("Input searching value x = "))
# pos=myList.findTheFirstPosOfNode(x)
# print(f"The 1st found of {x} is {pos}")
# print("\nSort the list")
# # myList.sortListAsc()
# myList.sortListDesc()
# myList.display()
print("\nFind post the-k of x")
x = int(input("Input searching value x = "))
k = int(input("Input the-k of x = "))
pos=myList.getPosOfNodeTheK(x, k)
if pos!=-1:
    print(f"The position the-{k} of {x}: {pos}")
else:
    print(f"Find not found the-{k} of {x}")