from DoubleLinkedList import DoubleLinkedList
myList=DoubleLinkedList()
myList.addFirst(6)
myList.addFirst(2)
myList.addFirst(8)
myList.addFirst(7)
myList.display()
print("\n")
myList.addLast(9)
myList.addLast(4)
myList.addLast(2)
myList.addLast(5)
myList.display()
print(f"\nNumber of nodes: {myList.countNode()}")
myList.removeFirst()
myList.display()
print("\nRemove Last")
myList.removeLast()
myList.display()
# print("\nAdd at pos")
# x = int(input("Input x = "))
# pos = int(input("Input position to add: "))
# myList.addAtPos(x, pos)
# myList.display()
# print("\nRemove at pos")
# pos = int(input("Input position to remove: "))
# myList.removeAtPos(pos)
# myList.display()
print("\nSort ASC/Desc")
# myList.sortAsc()
myList.sortDesc()
myList.display()
