from BSTree import BSTree
myT = BSTree()
myT.addATreeNode(9)
myT.addATreeNode(6)
myT.addATreeNode(12)
myT.addATreeNode(4)
myT.addATreeNode(2)
myT.addATreeNode(5)
myT.addATreeNode(1)
myT.addATreeNode(8)
myT.addATreeNode(11)
myT.addATreeNode(10)
myT.addATreeNode(18)
myT.inOrder(myT.root)
print("\nPreOrder---")
myT.preOrder(myT.root)
print("\nPostOrder---")
myT.postOrder(myT.root)
